// <auto-generated />
using System;
using DELTAAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DELTAAPI.Migrations
{
    [DbContext(typeof(DeltaTestContext))]
    partial class DeltaTestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DELTAAPI.Models.Area", b =>
                {
                    b.Property<int>("IdArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_area");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdArea"));

                    b.Property<string>("NombreArea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_area");

                    b.HasKey("IdArea")
                        .HasName("PK__AREA__8A8C837B5453672E");

                    b.HasIndex(new[] { "NombreArea" }, "UQ__AREA__1346D27AC7230296")
                        .IsUnique();

                    b.ToTable("AREA", (string)null);
                });

            modelBuilder.Entity("DELTAAPI.Models.Convocatorium", b =>
                {
                    b.Property<int>("IdConvocatoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_convocatoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConvocatoria"));

                    b.Property<string>("EstadoConvocatoria")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado_convocatoria");

                    b.Property<DateOnly?>("FechaConvocatoria")
                        .HasColumnType("date")
                        .HasColumnName("fecha_convocatoria");

                    b.Property<string>("NombreConvocatoria")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_convocatoria");

                    b.HasKey("IdConvocatoria")
                        .HasName("PK__CONVOCAT__2EAE64DB1B80B372");

                    b.ToTable("CONVOCATORIA", (string)null);
                });

            modelBuilder.Entity("DELTAAPI.Models.DatoAcademico", b =>
                {
                    b.Property<int>("IdDatoAcademico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_dato_academico");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDatoAcademico"));

                    b.Property<string>("Carrera")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("carrera");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("LugarEstudio")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("lugar_estudio");

                    b.Property<string>("TituloAcademico")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("titulo_academico");

                    b.HasKey("IdDatoAcademico")
                        .HasName("PK__DATO_ACA__AB51D4842666D8A3");

                    b.HasIndex("IdUsuario");

                    b.ToTable("DATO_ACADEMICO", (string)null);
                });

            modelBuilder.Entity("DELTAAPI.Models.Evaluacion", b =>
                {
                    b.Property<int>("IdEvaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_evaluacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvaluacion"));

                    b.Property<string>("EstadoEvaluacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado_evaluacion");

                    b.Property<DateOnly?>("FechaEvaluacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_evaluacion");

                    b.Property<int?>("IdAdministrador")
                        .HasColumnType("integer")
                        .HasColumnName("id_administrador");

                    b.Property<int?>("IdArea")
                        .HasColumnType("integer")
                        .HasColumnName("id_area");

                    b.Property<int>("IdEvaluado")
                        .HasColumnType("integer")
                        .HasColumnName("id_evaluado");

                    b.Property<decimal?>("Nota")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("nota");

                    b.Property<string>("Recomendaciones")
                        .HasColumnType("text")
                        .HasColumnName("recomendaciones");

                    b.Property<bool?>("TipoEvaluacion")
                        .HasColumnType("boolean")
                        .HasColumnName("tipo_evaluacion");

                    b.HasKey("IdEvaluacion")
                        .HasName("PK__EVALUACI__65DE60C5F6D38ADE");

                    b.HasIndex("IdAdministrador");

                    b.HasIndex("IdArea");

                    b.HasIndex("IdEvaluado");

                    b.ToTable("EVALUACION", (string)null);
                });

            modelBuilder.Entity("DELTAAPI.Models.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_notificacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotificacion"));

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_envio");

                    b.Property<int?>("IdAdministrador")
                        .HasColumnType("integer")
                        .HasColumnName("id_administrador");

                    b.Property<int?>("IdEvaluacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_evaluacion");

                    b.Property<int>("IdUsuarioDestino")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_destino");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<string>("TipoNotificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_notificacion");

                    b.HasKey("IdNotificacion")
                        .HasName("PK__NOTIFICA__8270F9A58C1F6715");

                    b.HasIndex("IdAdministrador");

                    b.HasIndex("IdEvaluacion");

                    b.HasIndex("IdUsuarioDestino");

                    b.ToTable("NOTIFICACION", (string)null);
                });

            modelBuilder.Entity("DELTAAPI.Models.Pregunta", b =>
                {
                    b.Property<int>("IdPregunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pregunta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPregunta"));

                    b.Property<int?>("IdEvaluacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_evaluacion");

                    b.Property<string>("Opciones")
                        .HasColumnType("text")
                        .HasColumnName("opciones");

                    b.Property<int>("Puntos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("puntos");

                    b.Property<int?>("RespuestaCorrectaIndex")
                        .HasColumnType("integer")
                        .HasColumnName("respuesta_correcta_index");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("texto");

                    b.Property<bool>("TipoEvaluacion")
                        .HasColumnType("boolean")
                        .HasColumnName("tipo_evaluacion");

                    b.HasKey("IdPregunta")
                        .HasName("PK__PREGUNTA__3C69FB99");

                    b.HasIndex("IdEvaluacion");

                    b.ToTable("PREGUNTA", (string)null);
                });

            modelBuilder.Entity("DELTAAPI.Models.Respuesta", b =>
                {
                    b.Property<int>("IdRespuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_respuesta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRespuesta"));

                    b.Property<int>("IdEvaluacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_evaluacion");

                    b.Property<int>("IdPregunta")
                        .HasColumnType("integer")
                        .HasColumnName("id_pregunta");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("TextoRespuesta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("texto_respuesta");

                    b.HasKey("IdRespuesta")
                        .HasName("PK__RESPUEST__1AAA640C");

                    b.HasIndex("IdEvaluacion");

                    b.HasIndex("IdPregunta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RESPUESTA", (string)null);
                });

            modelBuilder.Entity("DELTAAPI.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ci");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contraseña");

                    b.Property<string>("Correo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("correo");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<string>("Expedicion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("expedicion");

                    b.Property<DateOnly?>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<int?>("IdCreadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("id_creado_por");

                    b.Property<int?>("IdSupervisor")
                        .HasColumnType("integer")
                        .HasColumnName("id_supervisor");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("PuestoARotar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("puesto_a_rotar");

                    b.Property<string>("PuestoActual")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("puesto_actual");

                    b.Property<string>("PuestoSolicitado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("puesto_solicitado");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rol");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoEvaluado")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_evaluado");

                    b.HasKey("IdUsuario")
                        .HasName("PK__USUARIO__4E3E04AD77A0E458");

                    b.HasIndex("IdCreadoPor");

                    b.HasIndex("IdSupervisor");

                    b.HasIndex(new[] { "Correo" }, "UQ__USUARIO__2A586E0B2E389AD7")
                        .IsUnique();

                    b.HasIndex(new[] { "Ci" }, "UQ__USUARIO__32136662237C1C6E")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("EvaluadoConvocatorium", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdConvocatoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_convocatoria");

                    b.HasKey("IdUsuario", "IdConvocatoria")
                        .HasName("PK__EVALUADO__ECD4E2E08E56B8A5");

                    b.HasIndex("IdConvocatoria");

                    b.ToTable("EVALUADO_CONVOCATORIA", (string)null);
                });

            modelBuilder.Entity("DELTAAPI.Models.DatoAcademico", b =>
                {
                    b.HasOne("DELTAAPI.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("DatoAcademicos")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__DATO_ACAD__id_us__3D5E1FD2");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("DELTAAPI.Models.Evaluacion", b =>
                {
                    b.HasOne("DELTAAPI.Models.Usuario", "IdAdministradorNavigation")
                        .WithMany("EvaluacionIdAdministradorNavigations")
                        .HasForeignKey("IdAdministrador")
                        .HasConstraintName("FK__EVALUACIO__id_ad__49C3F6B7");

                    b.HasOne("DELTAAPI.Models.Area", "IdAreaNavigation")
                        .WithMany("Evaluacions")
                        .HasForeignKey("IdArea")
                        .HasConstraintName("FK__EVALUACIO__id_ar__4AB81AF0");

                    b.HasOne("DELTAAPI.Models.Usuario", "IdEvaluadoNavigation")
                        .WithMany("EvaluacionIdEvaluadoNavigations")
                        .HasForeignKey("IdEvaluado")
                        .IsRequired()
                        .HasConstraintName("FK__EVALUACIO__id_ev__48CFD27E");

                    b.Navigation("IdAdministradorNavigation");

                    b.Navigation("IdAreaNavigation");

                    b.Navigation("IdEvaluadoNavigation");
                });

            modelBuilder.Entity("DELTAAPI.Models.Notificacion", b =>
                {
                    b.HasOne("DELTAAPI.Models.Usuario", "IdAdministradorNavigation")
                        .WithMany("NotificacionIdAdministradorNavigations")
                        .HasForeignKey("IdAdministrador")
                        .HasConstraintName("FK__NOTIFICAC__id_ad__4E88ABD4");

                    b.HasOne("DELTAAPI.Models.Evaluacion", "IdEvaluacionNavigation")
                        .WithMany("Notificacions")
                        .HasForeignKey("IdEvaluacion")
                        .HasConstraintName("FK__NOTIFICAC__id_ev__4D94879B");

                    b.HasOne("DELTAAPI.Models.Usuario", "IdUsuarioDestinoNavigation")
                        .WithMany("NotificacionIdUsuarioDestinoNavigations")
                        .HasForeignKey("IdUsuarioDestino")
                        .IsRequired()
                        .HasConstraintName("FK__NOTIFICAC__id_us__4F7CD00D");

                    b.Navigation("IdAdministradorNavigation");

                    b.Navigation("IdEvaluacionNavigation");

                    b.Navigation("IdUsuarioDestinoNavigation");
                });

            modelBuilder.Entity("DELTAAPI.Models.Pregunta", b =>
                {
                    b.HasOne("DELTAAPI.Models.Evaluacion", "IdEvaluacionNavigation")
                        .WithMany("Preguntas")
                        .HasForeignKey("IdEvaluacion")
                        .HasConstraintName("FK_Pregunta_Evaluacion");

                    b.Navigation("IdEvaluacionNavigation");
                });

            modelBuilder.Entity("DELTAAPI.Models.Respuesta", b =>
                {
                    b.HasOne("DELTAAPI.Models.Evaluacion", "IdEvaluacionNavigation")
                        .WithMany("Respuestas")
                        .HasForeignKey("IdEvaluacion")
                        .IsRequired()
                        .HasConstraintName("FK_Respuesta_Evaluacion");

                    b.HasOne("DELTAAPI.Models.Pregunta", "IdPreguntaNavigation")
                        .WithMany("Respuestas")
                        .HasForeignKey("IdPregunta")
                        .IsRequired()
                        .HasConstraintName("FK_Respuesta_Pregunta");

                    b.HasOne("DELTAAPI.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Respuestas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Respuesta_Usuario");

                    b.Navigation("IdEvaluacionNavigation");

                    b.Navigation("IdPreguntaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("DELTAAPI.Models.Usuario", b =>
                {
                    b.HasOne("DELTAAPI.Models.Usuario", "IdCreadoPorNavigation")
                        .WithMany("InverseIdCreadoPorNavigation")
                        .HasForeignKey("IdCreadoPor")
                        .HasConstraintName("FK__USUARIO__id_crea__3A81B327");

                    b.HasOne("DELTAAPI.Models.Usuario", "IdSupervisorNavigation")
                        .WithMany("InverseIdSupervisorNavigation")
                        .HasForeignKey("IdSupervisor")
                        .HasConstraintName("FK__USUARIO__id_supe__398D8EEE");

                    b.Navigation("IdCreadoPorNavigation");

                    b.Navigation("IdSupervisorNavigation");
                });

            modelBuilder.Entity("EvaluadoConvocatorium", b =>
                {
                    b.HasOne("DELTAAPI.Models.Convocatorium", null)
                        .WithMany()
                        .HasForeignKey("IdConvocatoria")
                        .IsRequired()
                        .HasConstraintName("FK__EVALUADO___id_co__45F365D3");

                    b.HasOne("DELTAAPI.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__EVALUADO___id_us__44FF419A");
                });

            modelBuilder.Entity("DELTAAPI.Models.Area", b =>
                {
                    b.Navigation("Evaluacions");
                });

            modelBuilder.Entity("DELTAAPI.Models.Evaluacion", b =>
                {
                    b.Navigation("Notificacions");

                    b.Navigation("Preguntas");

                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("DELTAAPI.Models.Pregunta", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("DELTAAPI.Models.Usuario", b =>
                {
                    b.Navigation("DatoAcademicos");

                    b.Navigation("EvaluacionIdAdministradorNavigations");

                    b.Navigation("EvaluacionIdEvaluadoNavigations");

                    b.Navigation("InverseIdCreadoPorNavigation");

                    b.Navigation("InverseIdSupervisorNavigation");

                    b.Navigation("NotificacionIdAdministradorNavigations");

                    b.Navigation("NotificacionIdUsuarioDestinoNavigations");

                    b.Navigation("Respuestas");
                });
#pragma warning restore 612, 618
        }
    }
}
