-- Script para agregar las columnas faltantes a la tabla PREGUNTA

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PREGUNTA' AND COLUMN_NAME = 'puntos')
BEGIN
    ALTER TABLE [PREGUNTA]
    ADD [puntos] INT NOT NULL DEFAULT 0;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PREGUNTA' AND COLUMN_NAME = 'permite_eliminar_opciones')
BEGIN
    ALTER TABLE [PREGUNTA]
    ADD [permite_eliminar_opciones] BIT NOT NULL DEFAULT 1;
END

-- Verifica que las columnas fueron creadas correctamente
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PREGUNTA' ORDER BY ORDINAL_POSITION;
